### PR TITLE
Replace cscs_retrieve with jretrievedwh

### PR DESCRIPTION
**Pull request by leuty**
cscs_retrieve got retired by osm. jretrievedwh  is the replacement

manual testing done:
Created a timeseries plot

### CODE REVIEW

**Comment by leuty** [comment]
launch jenkins

**Comment by swester** [comment]
the command for the integrated profiles does not work as it is currently implemented. 
the --show_records has to be removed.

oprusers/osm/bin/jretrievedwh --show_records -j lat,lon,name -s profile_integral -i int_ind,06610 -p 5547 -t 202302140000-202302140800 -C 38 -w 31

**Comment by swester** [comment]
for the surface obs it seems to be a valid argument still, but probably not needed.

**Comment by leuty** [comment]
Thx for the testing. Just to make sure that I understand your proposal:

The record length obtained from `--show records` is used to check if no data has been retrieved:
https://github.com/leuty/plot_profile/blob/020b2330f8e3877db513bfc482d717a581a7931c/src/plot_profile/utils/dwh_retrieve.py#L178-L186

But it is not needed since further below we check for an empty data frame:

https://github.com/leuty/plot_profile/blob/020b2330f8e3877db513bfc482d717a581a7931c/src/plot_profile/utils/dwh_retrieve.py#L200-L218

So you are proposing to remove the first check and `--show-records`, correct?

**Comment by swester** [comment]
I've just tested again, and today the `--show_records` does not produce any problems when retrieving profile_integral data. 0.0
I've asked Petra, but she does not know the answer to this and does not experience frequent problems with this switch. So I suggest to just keep it as is currently, and merge the pull request. 👍

**Comment by swester** [comment]
Thanks for your help :-)

**Pull request merged**
